const exportFields = {
  circheatmap: [
    'analysis',
    'circles',
    'display',
    'gprofiler',
    'labels',
    'panel',
    'parameters',
    'plots',
    'poi',
    'readouts',
    'searchStatus',
    'settings',
    'tabs',
  ],
  heatmap: [
    'analysis',
    'annotations',
    'columnDB',
    'columns',
    'display',
    'exporter',
    'gprofiler',
    'markers',
    'minimap',
    'panel',
    'parameters',
    'poi',
    'position',
    'rowDB',
    'rows',
    'searchStatus',
    'settings',
    'tabs',
  ],
  scatter: [
    'analysis',
    'customization',
    'display',
    'gprofiler',
    'labels',
    'legend',
    'lines',
    'panel',
    'parameters',
    'plots',
    'poi',
    'points',
    'searchStatus',
    'settings',
    'tabs',
  ],
};

export default exportFields;
