import PropTypes from 'prop-types';
import React from 'react';

import File from './utilities-file';
import LoadUtility from './load-utility';
import Select from './utility-select';
import Submit from './utilities-submit';

import './utilities.css';

const Utilities = ({
  handleInputFile,
  handleSubmit,
  handleUtilityType,
  utility,
}) => (
  <div className="utilities">
    <div className="utilities__inner">
      <h1>Utilities</h1>
      <p>
        Here you can find additional utilities for working with files from ProHits-viz, as well as miscellaneous tools
        for analysis.
      </p>
      <p>
        Many of the scripts supporting these utilities were generated by us for previous research projects. Most involve
        extracting and processing data from protein-protein interaction files (typically SAINT). These utilities may
        output tabular data files or static images. While these utilities do no warrant full interactive support, such
        as the other tools at ProHits-viz, we include them here as they may be of use to others.
      </p>
      <p>
        <strong>
          The page is a work in progress, and more utilities will be added in the near future.
        </strong>
      </p>
      <File handleInputFile={handleInputFile} />
      <Select
        handleUtilityType={handleUtilityType}
        utility={utility}
      />
      <LoadUtility utility={utility} />
      <Submit
        handleSubmit={handleSubmit}
        utility={utility}
      />
    </div>
  </div>
);

Utilities.defaultProps = {
  utility: '',
};

Utilities.propTypes = {
  handleInputFile: PropTypes.func.isRequired,
  handleSubmit: PropTypes.func.isRequired,
  handleUtilityType: PropTypes.func.isRequired,
  utility: PropTypes.string,
};

export default Utilities;
