const recommendedColumns = {
  'condition-condition': {
    crapome: {
      abundance: ['avgspc', 'avg. spc', 'avgint', 'avg. int'],
      condition: ['bait', 'baitgene'],
      control: ['user controls (spc or intensities)', 'crap controls (spc)', 'crap controls (int)'],
      readout: ['prey', 'preygene'],
      readoutLength: ['preysequencelength'],
      score: ['bfdr', 'fdr', 'sp', 'fca', 'fcb', 'wd', 'is'],
    },
    other: {
      abundance: ['abundance', 'abundances', 'avgspec', 'specsum', 'avgintensity', 'intensitysum'],
      condition: ['condition', 'conditions', 'bait', 'baits'],
      control: ['control', 'controls', 'ctrlcounts'],
      readout: ['readout', 'readouts', 'preygene', 'prey', 'preygenes', 'preys'],
      readoutLength: ['readoutLength', 'readoutLengths', 'preysequencelength'],
      score: ['score', 'scores', 'pvalue', 'p-value', 'confidence', 'bfdr', 'fdr', 'saintscore', 'avgp', 'maxp'],
    },
    saint: {
      abundance: ['avgspec', 'specsum', 'avgintensity', 'intensitysum'],
      condition: ['bait', 'baits'],
      control: ['ctrlcounts', 'control', 'controls'],
      readout: ['preygene', 'prey', 'preygenes', 'preys'],
      readoutLength: ['preysequencelength'],
      score: ['bfdr', 'fdr', 'saintscore', 'avgp', 'maxp'],
    },
  },
  correlation: {
    crapome: {
      abundance: ['avgspc', 'avg. spc', 'avgint', 'avg. int'],
      condition: ['bait', 'baitgene'],
      control: ['user controls (spc or intensities)', 'crap controls (spc)', 'crap controls (int)'],
      readout: ['prey', 'preygene'],
      readoutLength: ['preysequencelength'],
      score: ['bfdr', 'fdr', 'sp', 'fca', 'fcb', 'wd', 'is'],
    },
    other: {
      abundance: ['abundance', 'abundances', 'avgspec', 'specsum', 'avgintensity', 'intensitysum'],
      condition: ['condition', 'conditions', 'bait', 'baits'],
      control: ['control', 'controls', 'ctrlcounts'],
      readout: ['readout', 'readouts', 'preygene', 'prey', 'preygenes', 'preys'],
      readoutLength: ['readoutLength', 'readoutLengths', 'preysequencelength'],
      score: ['score', 'scores', 'pvalue', 'p-value', 'confidence', 'bfdr', 'fdr', 'saintscore', 'avgp', 'maxp'],
    },
    saint: {
      abundance: ['spec', 'avgspec', 'specsum', 'avgintensity', 'intensitysum'],
      condition: ['bait', 'baits'],
      control: ['ctrlcounts', 'control', 'controls'],
      readout: ['preygene', 'prey', 'preygenes', 'preys'],
      readoutLength: ['preysequencelength'],
      score: ['bfdr', 'fdr', 'saintscore', 'avgp', 'maxp'],
    },
  },
  dotplot: {
    crapome: {
      abundance: ['avgspc', 'avg. spc', 'avgint', 'avg. int'],
      condition: ['bait', 'baitgene'],
      control: ['user controls (spc or intensities)', 'crap controls (spc)', 'crap controls (int)'],
      readout: ['prey', 'preygene'],
      readoutLength: ['preysequencelength'],
      score: ['bfdr', 'fdr', 'sp', 'fca', 'fcb', 'wd', 'is'],
    },
    other: {
      abundance: ['abundance', 'abundances', 'avgspec', 'specsum', 'avgintensity', 'intensitysum'],
      condition: ['condition', 'conditions', 'bait', 'baits'],
      control: ['control', 'controls', 'ctrlcounts'],
      readout: ['readout', 'readouts', 'preygene', 'prey', 'preygenes', 'preys'],
      readoutLength: ['readoutLength', 'readoutLengths', 'preysequencelength'],
      score: ['score', 'scores', 'pvalue', 'p-value', 'confidence', 'bfdr', 'fdr', 'saintscore', 'avgp', 'maxp'],
    },
    saint: {
      abundance: ['avgspec', 'specsum', 'avgintensity', 'intensitysum'],
      condition: ['bait', 'baits'],
      control: ['ctrlcounts', 'control', 'controls'],
      readout: ['preygene', 'prey', 'preygenes', 'preys'],
      readoutLength: ['preysequencelength'],
      score: ['bfdr', 'fdr', 'saintscore', 'avgp', 'maxp'],
    },
  },
  scv: {
    crapome: {
      abundance: ['avgspc', 'avg. spc', 'avgint', 'avg. int'],
      condition: ['bait', 'baitgene'],
      control: ['user controls (spc or intensities)', 'crap controls (spc)', 'crap controls (int)'],
      readout: ['prey', 'preygene'],
      readoutLength: ['preysequencelength'],
      score: ['bfdr', 'fdr', 'sp', 'fca', 'fcb', 'wd', 'is'],
    },
    other: {
      abundance: ['abundance', 'abundances', 'avgspec', 'specsum', 'avgintensity', 'intensitysum'],
      condition: ['condition', 'conditions', 'bait', 'baits'],
      control: ['control', 'controls', 'ctrlcounts'],
      readout: ['readout', 'readouts', 'preygene', 'prey', 'preygenes', 'preys'],
      readoutLength: ['readoutLength', 'readoutLengths', 'preysequencelength'],
      score: ['score', 'scores', 'pvalue', 'p-value', 'confidence', 'bfdr', 'fdr', 'saintscore', 'avgp', 'maxp'],
    },
    saint: {
      abundance: ['avgspec', 'foldchange', 'uniquespec', 'avgintensity', 'intensitysum'],
      condition: ['bait', 'baits'],
      control: ['ctrlcounts', 'control', 'controls'],
      readout: ['preygene', 'prey', 'preygenes', 'preys'],
      readoutLength: ['preysequencelength'],
      score: ['bfdr', 'fdr', 'saintscore', 'avgp', 'maxp'],
    },
  },
  specificity: {
    crapome: {
      abundance: ['avgspc', 'avg. spc', 'avgint', 'avg. int'],
      condition: ['bait', 'baitgene'],
      control: ['user controls (spc or intensities)', 'crap controls (spc)', 'crap controls (int)'],
      readout: ['prey', 'preygene'],
      readoutLength: ['preysequencelength'],
      score: ['bfdr', 'fdr', 'sp', 'fca', 'fcb', 'wd', 'is'],
    },
    other: {
      abundance: ['abundance', 'abundances', 'avgspec', 'specsum', 'avgintensity', 'intensitysum'],
      condition: ['condition', 'conditions', 'bait', 'baits'],
      control: ['control', 'controls', 'ctrlcounts'],
      readout: ['readout', 'readouts', 'preygene', 'prey', 'preygenes', 'preys'],
      readoutLength: ['readoutLength', 'readoutLengths', 'preysequencelength'],
      score: ['score', 'scores', 'pvalue', 'p-value', 'confidence', 'bfdr', 'fdr', 'saintscore', 'avgp', 'maxp'],
    },
    saint: {
      abundance: ['avgspec', 'specsum', 'avgintensity', 'intensitysum', 'spec'],
      condition: ['bait', 'baits'],
      control: ['ctrlcounts', 'control', 'controls'],
      readout: ['preygene', 'prey', 'preygenes', 'preys'],
      readoutLength: ['preysequencelength'],
      score: ['bfdr', 'fdr', 'saintscore', 'avgp', 'maxp'],
    },
  },
};

export default recommendedColumns;
