const common = [
  'abundance',
  'condition',
  'control',
  'ctrlSub',
  'logBase',
  'minConditions',
  'mockConditionAbundance',
  'normalization',
  'normalizationReadout',
  'parsimoniousReadoutFiltering',
  'readout',
  'readoutLength',
  'readoutLengthNorm',
  'sampleFile',
  'score',
  'scoreType',
  'png',
];

const fields = {
  correlation: [
    ...common,
    'clustering',
    'clusteringMethod',
    'clusteringOptimize',
    'conditionAbundanceFilter',
    'conditionScoreFilter',
    'correlation',
    'cytoscapeCutoff',
    'distance',
    'fillColor',
    'ignoreSourceTargetMatches',
    'readoutAbundanceFilter',
    'readoutScoreFilter',
    'useReplicates',
  ],
  dotplot: [
    ...common,
    'abundanceCap',
    'biclusteringApprox',
    'clustering',
    'clusteringMethod',
    'clusteringOptimize',
    'conditionClustering',
    'conditionList',
    'distance',
    'edgeColor',
    'fillColor',
    'minAbundance',
    'primaryFilter',
    'readoutClustering',
    'readoutList',
    'secondaryFilter',
    'writeDistance',
    'writeHeatmap',
  ],
};

export default fields;
