const common = [
  'abundance',
  'condition',
  'control',
  'ctrlSub',
  'logBase',
  'mockConditionAbundance',
  'normalization',
  'normalizationReadout',
  'readout',
  'readoutLength',
  'readoutLengthNorm',
  'sampleFile',
  'score',
  'scoreType',
  'png',
];

const fields = {
  'condition-condition': [
    ...common,
    'conditionX',
    'conditionY',
    'minAbundance',
    'primaryFilter',
    'secondaryFilter',
  ],
  correlation: [
    ...common,
    'clustering',
    'clusteringMethod',
    'clusteringOptimize',
    'conditionAbundanceFilter',
    'conditionScoreFilter',
    'correlation',
    'cytoscapeCutoff',
    'distance',
    'fillColor',
    'ignoreSourceTargetMatches',
    'minConditions',
    'parsimoniousReadoutFiltering',
    'readoutAbundanceFilter',
    'readoutScoreFilter',
    'useReplicates',
  ],
  dotplot: [
    ...common,
    'abundanceCap',
    'biclusteringApprox',
    'clustering',
    'clusteringMethod',
    'clusteringOptimize',
    'conditionClustering',
    'conditionList',
    'distance',
    'edgeColor',
    'fillColor',
    'minAbundance',
    'minConditions',
    'parsimoniousReadoutFiltering',
    'primaryFilter',
    'readoutClustering',
    'readoutList',
    'secondaryFilter',
    'writeDistance',
    'writeHeatmap',
  ],
  scv: [
    ...common,
    'abundanceCap',
    'abundanceFilterColumn',
    'conditionIDType',
    'conditionMapColumn',
    'conditionMapFile',
    'known',
    'minAbundance',
    'otherAbundance',
    'primaryFilter',
    'proteinTissues',
    'readoutIDType',
    'readoutMapColumn',
    'readoutMapFile',
    'rnaTissues',
    'specificity',
    'verticalHeatmap',
  ],
  specificity: [
    ...common,
    'minAbundance',
    'specificityMetric',
  ],
};

export default fields;
