const sampleHeader = 'Bait\tPrey\tPreyGene\tSpec\tSpecSum\tAvgSpec\tNumReplicates\t'
+ 'ctrlCounts\tAvgP\tMaxP\tTopoAvgP\tTopoMaxP\tSaintScore\tlogOddsScore\tFoldChange\t'
+ 'BFDR\tUniqueSpec\tUniqueSpecSum\tUniqueAvgSpec\tPreySequenceLength\n'
+ 'AMOT_HeLa\t\n'
+ 'ANKRD28\t\n'
+ 'BirA_CTTNBP3NL\t\n'
+ 'LATS1\t\n'
+ 'LATS1_Hela\t\n'
+ 'Lats2\t\n'
+ 'Lats2_HeLa\t\n'
+ 'MOB1A\t\n'
+ 'MOB1B\t\n'
+ 'PPP6R1\t\n'
+ 'PPP6R2\t\n'
+ 'PPP6R3\t\n'
+ 'RASSF2\t\n'
+ 'SAV1\t\n'
+ 'SLMAP\t\n'
+ 'STK3\t\n'
+ 'STK3_HeLa\t\n'
+ 'STK4\t\n'
+ 'STK4_HeLa\t\n'
+ 'STRN3_HeLa\t\n'
+ 'Strn\t\n'
+ 'Strn_HeLa\t\n'
+ 'TJP2_HeLa\t\n'
+ 'YAP1_HeLa\t\n';

export default sampleHeader;
